# Generated by Django 2.0 on 2017-12-09 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_occurred', models.DateField()),
                ('incident_type', models.CharField(choices=[('BU', 'Bullying'), ('HO', 'Homework'), ('LC', 'Late-coming'), ('SM', 'Smoking')], max_length=3)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('TE', 'Telephone'), ('SM', 'SMS'), ('WH', 'WhatsApp'), ('EM', 'EMAIL'), ('ME', 'Meeting')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Incident')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('guardian', models.CharField(blank=True, max_length=50)),
                ('mode_of_transport', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
