# Generated by Django 2.0 on 2017-12-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mode_of_transport',
            field=models.CharField(blank=True, choices=[('BU', 'Bus'), ('TA', 'Taxi'), ('TR', 'Train')], max_length=3),
        ),
    ]
