# Generated by Django 2.0 on 2017-12-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20171209_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['student', '-status', '-date_occurred']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_names']},
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('Bullying', 'Bullying'), ('Homework', 'Homework'), ('Late-coming', 'Late-coming'), ('Smoking', 'Smoking')], max_length=15),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('Telephone', 'Telephone'), ('SMS', 'SMS'), ('Whatsapp', 'WhatsApp'), ('Email', 'EMAIL'), ('Meeting', 'Meeting')], max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='mode_of_transport',
            field=models.CharField(blank=True, choices=[('Bus', 'Bus'), ('Taxi', 'Taxi'), ('Train', 'Train')], max_length=10),
        ),
    ]
