# Generated by Django 2.0 on 2017-12-09 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20171209_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='date_interaction',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
